services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper


  ais-ws-broadcaster:
    build:
      context: ./ais/ws-broadcaster
      dockerfile: Dockerfile
    container_name: ais_ws_broadcaster
    environment:
      - KAFKA_ADDRESS=kafka:9092
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - kafka

  ais-repository:
    build:
      context: ./ais/repository
      dockerfile: Dockerfile
    container_name: ais_repository
    environment:
      - KAFKA_ADDRESS=kafka:9092
      - MAX_HISTORY_RECORDS_PER_SHIP=100
    restart: unless-stopped
    depends_on:
      - ais-ws-broadcaster

  ais-ingestor:
    build:
      context: ./ais/ingestor
      dockerfile: Dockerfile
    container_name: ais_ingestor
    environment:
      - KAFKA_ADDRESS=kafka:9092
    restart: unless-stopped
    depends_on:
      - ais-repository

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    container_name: controller
    ports:
      - "8080:8080"
    environment:
      - ML_SERVICE_URL=http://ml:8080
      - REPOSITORY_SERVICE_URL=http://ais-repository:8080
      - BROADCASTER_SERVICE_URL=http://ais-ws-broadcaster:5000
    restart: unless-stopped

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml
    restart: unless-stopped

