CREATE TABLE ship_type (
    type_code INT PRIMARY KEY,
    type_name VARCHAR(100) NOT NULL
);

CREATE TABLE ship_static_data (
    message_id INTEGER,
    repeat_indicator INTEGER,
    mmsi BIGINT PRIMARY KEY,
    valid BOOLEAN,
    ais_version INTEGER,
    imo_number INTEGER,
    call_sign TEXT,
    name TEXT,
    ship_type INTEGER,
    dimensions JSONB,
    fix_type INTEGER,
    eta JSONB,
    max_static_draught REAL,
    destination TEXT,
    dte BOOLEAN,
    spare BOOLEAN,
    ship_length INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ship_static_data_mmsi ON ship_static_data(mmsi);

ALTER TABLE ship_static_data
    ADD CONSTRAINT fk_ship_type
    FOREIGN KEY (ship_type)
    REFERENCES ship_type(type_code);


-- Populate the type table --
INSERT INTO ship_type (type_code, type_name) VALUES
(0, 'Not available'),
(1, 'Reserved for future use'),
(2, 'Reserved for future use'),
(3, 'Reserved for future use'),
(4, 'Reserved for future use'),
(5, 'Reserved for future use'),
(6, 'Reserved for future use'),
(7, 'Reserved for future use'),
(8, 'Reserved for future use'),
(9, 'Reserved for future use'),
(10, 'Reserved for future use'),
(11, 'Reserved for future use'),
(12, 'Reserved for future use'),
(13, 'Reserved for future use'),
(14, 'Reserved for future use'),
(15, 'Reserved for future use'),
(16, 'Reserved for future use'),
(17, 'Reserved for future use'),
(18, 'Reserved for future use'),
(19, 'Reserved for future use'),
(20, 'Wing In Ground Craft (WIG), all ships of this type'),
(21, 'Wing In Ground Craft (WIG), Hazardous category A'),
(22, 'Wing In Ground Craft (WIG), Hazardous category B'),
(23, 'Wing In Ground Craft (WIG), Hazardous category C'),
(24, 'Wing In Ground Craft (WIG), Hazardous category D'),
(25, 'Wing In Ground Craft (WIG), Reserved'),
(26, 'Wing In Ground Craft (WIG), Reserved'),
(27, 'Wing In Ground Craft (WIG), Reserved'),
(28, 'Wing In Ground Craft (WIG), Reserved'),
(29, 'Wing In Ground Craft (WIG), Reserved'),
(30, 'Fishing'),
(31, 'Towing'),
(32, 'Towing: length >200m or breadth >25m'),
(33, 'Dredging or underwater ops'),
(34, 'Diving ops'),
(35, 'Military ops'),
(36, 'Sailing'),
(37, 'Pleasure craft'),
(38, 'Reserved'),
(39, 'Reserved'),
(40, 'High Speed Craft (HSC), all ships of this type'),
(41, 'High Speed Craft (HSC), Hazardous category A'),
(42, 'High Speed Craft (HSC), Hazardous category B'),
(43, 'High Speed Craft (HSC), Hazardous category C'),
(44, 'High Speed Craft (HSC), Hazardous category D'),
(45, 'High Speed Craft (HSC), Reserved'),
(46, 'High Speed Craft (HSC), Reserved'),
(47, 'High Speed Craft (HSC), Reserved'),
(48, 'High Speed Craft (HSC), Reserved'),
(49, 'High Speed Craft (HSC), Reserved'),
(50, 'Pilot vessel'),
(51, 'Search and rescue vessel'),
(52, 'Tug'),
(53, 'Port tender'),
(54, 'Anti-pollution equipment'),
(55, 'Law enforcement vessel'),
(56, 'Spare'),
(57, 'Spare'),
(58, 'Spare'),
(59, 'Spare'),
(60, 'Passenger ship'),
(61, 'Passenger ship, Hazardous category A'),
(62, 'Passenger ship, Hazardous category B'),
(63, 'Passenger ship, Hazardous category C'),
(64, 'Passenger ship, Hazardous category D'),
(65, 'Passenger ship, Reserved'),
(66, 'Passenger ship, Reserved'),
(67, 'Passenger ship, Reserved'),
(68, 'Passenger ship, Reserved'),
(69, 'Passenger ship, Reserved'),
(70, 'Cargo ship'),
(71, 'Cargo ship, Hazardous category A'),
(72, 'Cargo ship, Hazardous category B'),
(73, 'Cargo ship, Hazardous category C'),
(74, 'Cargo ship, Hazardous category D'),
(75, 'Cargo ship, Reserved'),
(76, 'Cargo ship, Reserved'),
(77, 'Cargo ship, Reserved'),
(78, 'Cargo ship, Reserved'),
(79, 'Cargo ship, Reserved'),
(80, 'Tanker'),
(81, 'Tanker, Hazardous category A'),
(82, 'Tanker, Hazardous category B'),
(83, 'Tanker, Hazardous category C'),
(84, 'Tanker, Hazardous category D'),
(85, 'Tanker, Reserved'),
(86, 'Tanker, Reserved'),
(87, 'Tanker, Reserved'),
(88, 'Tanker, Reserved'),
(89, 'Tanker, Reserved'),
(90, 'Other types of ship'),
(91, 'Medical transport'),
(92, 'Ship carrying dangerous goods'),
(93, 'Ship carrying harmful substances'),
(94, 'Ship carrying IMO hazard category A'),
(95, 'Ship carrying IMO hazard category B'),
(96, 'Ship carrying IMO hazard category C'),
(97, 'Ship carrying IMO hazard category D'),
(98, 'Ship carrying hazardous cargo, type unknown'),
(99, 'Other special category ship');
