services:

  ais-ws-broadcaster:
    build:
      context: ./ais/ws-broadcaster
      dockerfile: Dockerfile
    env_file:
      - ./ais/ws-broadcaster/.env
    container_name: ais_ws_broadcaster
    ports:
      - "5000:5000"
    restart: unless-stopped

  ais-repository:
    build:
      context: ./ais/repository
      dockerfile: Dockerfile
    env_file:
      - ./ais/repository/.env
    container_name: ais_repository
    restart: unless-stopped
    depends_on:
      - ais-ws-broadcaster

  ais-ingestor:
    build:
      context: ./ais/ingestor
      dockerfile: Dockerfile
    env_file:
      - ./ais/ingestor/.env
    container_name: ais_ingestor
    restart: unless-stopped
    depends_on:
      - ais-repository

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Main edge port for all services
      - "4571:4571"   # Optional: pro metrics
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LS_LOG=info
    volumes:
      - "localstack_data:/var/lib/localstack"        # persistent data
      - "/var/run/docker.sock:/var/run/docker.sock"  # enables some emulation features
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -s http://localhost:4566/health | grep -q '\"initialized\": true'"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    env_file:
      - ./controller/.env
    container_name: controller
    ports:
      - "8080:8080"
    restart: unless-stopped

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml
    restart: unless-stopped

volumes:
  localstack_data:

