services:

  ais-ws-broadcaster:
    image: 822491881272.dkr.ecr.us-east-2.amazonaws.com/ais-ws-broadcaster:latest
    container_name: ais_ws_broadcaster
    environment:
      WS_API_KEY: ${WS_API_KEY}
      AWS_REGION: ${AWS_REGION}
      SQS_URL: ${SQS_URL}
    ports:
      - "5000:5000"
    restart: unless-stopped

  ais-repository:
    image: 822491881272.dkr.ecr.us-east-2.amazonaws.com/ais-repository:latest
    container_name: ais_repository
    environment: 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - ais-ws-broadcaster
    restart: unless-stopped

  ais-ingestor:
    image: 822491881272.dkr.ecr.us-east-2.amazonaws.com/ais-ingestor:latest
    container_name: ais_ingestor
    environment: 
      AIS_MESSAGE_BATCH_SIZE: ${AIS_MESSAGE_BATCH_SIZE}
      WS_API_KEY: ${WS_API_KEY}
      AWS_REGION: ${AWS_REGION}
      SNS_TOPIC_ARN: ${SNS_TOPIC_ARN}
    depends_on:
      - ais-repository
    restart: unless-stopped
