services:

  postgis-db:
    image: postgis/postgis
    container_name: postgis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ais_data
    ports:
      - "5432:5432"
    volumes:
      - ./db/db/init:/docker-entrypoint-initdb.d
      - /mnt/pgdata:/var/lib/postgresql/data
      - ./db/db/data:/data
    restart: unless-stopped

  ais-ws-broadcaster:
    image: 822491881272.dkr.ecr.us-east-2.amazonaws.com/ais-ws-broadcaster:latest
    container_name: ais_ws_broadcaster
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  ais-repository:
    image: 822491881272.dkr.ecr.us-east-2.amazonaws.com/ais-repository:latest
    container_name: ais_repository
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgis-db
    restart: unless-stopped

  ais-ingestor:
    image: 822491881272.dkr.ecr.us-east-2.amazonaws.com/ais-ingestor:latest
    container_name: ais_ingestor
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - ais-repository
    restart: unless-stopped

volumes:
  pgdata:
